/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class PlanetsControllerTest {
    @Test public void testSomeLibraryMethod() {
     //   PlanetsController classUnderTest = new PlanetsController();
       
    }
}
