
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.skilldistillery.MVCCRUDProject.controllers;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.SessionAttributes;
import org.springframework.web.servlet.ModelAndView;

import com.skilldistillery.MVCCRUDProject.Planet;
import com.skilldistillery.MVCCRUDProject.PlanetDAO;

@Controller
@SessionAttributes("planetData")
public class PlanetsController {

	@Autowired
	private PlanetDAO planetDAO;

	public PlanetDAO getPlanetDAO() {
		return planetDAO;
	}

	public void setPlanetDAO(PlanetDAO planetDAO) {
		this.planetDAO = planetDAO;
	}

	// GetPlanetData.do? planetname
	@RequestMapping(path = "GetAllPlanets.do", method = RequestMethod.GET)
	public ModelAndView getAllPlanets() {

		ModelAndView mv = new ModelAndView();
		List<Planet> planets = planetDAO.getAllPlanets(); // returns a list of planets to index.jsp

		if (planets != null) {

			mv.addObject("planetData", planets);
		}
		mv.setViewName("/WEB-INF/views/index.jsp");
		return mv;
	}

	// GetPlanetData.do? planetname
	@RequestMapping(path = "GetPlanetData.do", params = "planetname", method = RequestMethod.GET)
	public ModelAndView getPlanet(@RequestParam("planetname") String n) {

		System.out.println("getPlanetNamne: " + n);
		ModelAndView mv = new ModelAndView();
		Planet planet = planetDAO.getPlanet(n);
		System.out.println(planet);
		if (planet != null) {
			System.out.println("AddObject " + planet);
			mv.addObject("planetData", planet);
		}
		mv.setViewName("/WEB-INF/views/result.jsp");
		return mv;
	}

	

	@RequestMapping(path = "PlanetAdded.do", method = RequestMethod.POST)
	public ModelAndView addPlanet(Planet planet) {
		ModelAndView mv = new ModelAndView();
		System.out.println("Controller: addPlanet()");
		planetDAO.addPlanet(planet);
		mv.setViewName("redirect:GetAllPlanets.do");
		mv.addObject("planetData", planet);
		return mv;

	}

	@RequestMapping(path = "PlanetUpdated.do", method = RequestMethod.POST)
	public ModelAndView updatePlanet(Planet planet) {
		System.out.println("update planet in controller");
		ModelAndView mv = new ModelAndView();
		planetDAO.updatePlanet(planet);
		mv.setViewName("redirect:GetAllPlanets.do");
		return mv;

	}

	@RequestMapping(path = "RemovePlanetData.do", method = RequestMethod.POST)
	public ModelAndView removePlanet(@RequestParam("planetname") String s) {
		ModelAndView mv = new ModelAndView();
		mv.setViewName("/WEB-INF/views/planetremoved.jsp");
		if (planetDAO.removePlanet(s) != null) {
			mv.addObject("planetName", s);
		}
		return mv;
	}

}
